### ISSUE TITLE
Include a minimal example on how to use?

### ISSUE THREAD

**Issue by TerrorJack** [tolysz/prepare-ghcjs#2]
How to use this tool to generate a ghcjs tarball for a specified nightly/lts snapshot? Thanks!

**Comment by tolysz** [comment]
It is currently "designed" for one user. 

I compile it and run via `cron`. 
But the minimal will be: 
clone

> `stack ghci`
> `syncLts`
latest lts
> `syncNightly`
latest nightly
> `sync (ltsCfg {checkResolver = return "bla-123.456"})`
for resolver bla-123.456

the output should be in the archive.

This is very manual, In the ideal world all changes here should go to `ghcjs/ghcjs` or to upstream packages
I upload my builds thus I have `ghcjs-host` entry in `~/.ssh/config` 

I still explore the design space. The operation on `boot` packages should be:
override_by_copy
copy_from_hackage
copy_from_boot
patch_hackage

some of them might generate new dependencies in `boot.yaml`

**Comment by tolysz** [comment]
This is really hardcore :) I ma trying to boot lts-8... I am not sure how the description for it should looks like
