### ISSUE TITLE
Support for stackage snapshots > lts-8.0

### ISSUE THREAD

**Issue by matchwood** [tolysz/prepare-ghcjs#6]
I'd like to use the latest lts (currently 8.4) with ghcjs (see here http://stackoverflow.com/posts/42720347/), and I've been trying to use prepare-ghcjs to do this. There are a couple of changes in the latest ghcjs that need a bit of tweaking:
1) The inclusion of npm in build.yaml
2) shelly and haddock-api version bumps for the ghcjs stack.yaml - the haddock-api version required is actually broken, so we need to use something like the config here https://github.com/matchwood/prepare-ghcjs/blob/master/spec-lts/stack.yaml .

I've managed to get that far, but when ghcjs boot runs there is an error compiling base:

    GHC/TopHandler.hs:88:29: error:
      Data constructor not in scope: STG_SIG_RST :: CInt

I'm happy to spend a bit of time to hack around and get a working PR but I'd really appreciate some input, as I'm not really sure where to start in terms of how to find out why this error is happening.

**Comment by matchwood** [comment]
I've been poking around, and the issue is that lts-8.0+ use base 4.9.1.0 rather than 4.9.0.0, so the patches luite uses have not been applied. The underlying issue is really that https://github.com/ghcjs/ghcjs-boot needs to be updated to support the packages that lts-8.0+ need, as doubtless would be obvious to anyone familiar with this area! I'll close this issue and perhaps start hacking away on ghcjs-boot instead...

**Comment by tolysz** [comment]
Yes, it would be nice to have a branch per resolver on the ghcjs

**Comment by matchwood** [comment]
I'll try to get a ghcjs-boot working for 8.0. As far as I can tell so far most of the work is bumping upper bounds and tweaking the existing patches - does that sound about right?

**Comment by tolysz** [comment]
;) Yes it does.
Start with the base i.e. create a patch with diff, vanila-base-4.9.0.0 -> base-4.9.0.0, then try to apply it with base-4.9.1.0... there is a lot of bumping to be done. Aeson is still not useful.

**Comment by matchwood** [comment]
What fun! 

I'm not sure what you mean by aeson not being useful though... difficult to get the lts package version in because it is too far ahead?

**Comment by matchwood** [comment]
So I've managed to get something working.
https://github.com/matchwood/ghcjs/tree/lts-8.0 and
https://github.com/matchwood/ghcjs-boot/tree/lts-8.0

It fails a few tests ( https://github.com/ghcjs/ghcjs/issues/571) but I created an sdist tar.gz and tested it with a fresh .stack / .ghcjs and it succesfully installs and compiles reflex and a little test app.

I also hacked together a quick fix for longlinks in the cache .tar archives (https://github.com/matchwood/ghcjs/commit/99fc29dc88725c86ae479bd6c27f4e6089abf052) because they actually broke the installation process.

I'd like to make the bundle for lts-8.0 available - any ideas? I was wondering if perhaps you could host it in the same place as the others? I can make a pr request on the stack docs to refer to it - I'd hate to think of someone else having to scramble up the learning curve I've just been on, particularly when testing something like ghcjs-boot!
